### ISSUE TITLE
Feature Request: Make Ve available as a standalone app via TrollStore

### ISSUE THREAD

**Issue by fzltfzlt** [AlexandraAurora/Ve#15]
Hello AlexandraAurora,

Firstly, I would like to express my gratitude for the fantastic work you've done on the Ve project. I've been following your project closely, and I'm genuinely impressed with the features it offers.

**Feature Request:** I was wondering if there's a possibility to develop Ve into a standalone application that can be installed via TrollStore? Such a feature would make Ve more accessible and user-friendly, especially for users who are unable to jailbreak their devices.

I understand that this may require additional development work and resources. If there's any way I can assist, or if further discussion on this idea is needed, please let me know.

Thank you once again for your hard work, and I look forward to your response.

Best regards

**Comment by AlexandraAurora** [comment]
Thanks for the kind words. Sadly, I rarely ever work on jailbreak stuff anymore, so I won't be doing this. I'm pretty sure it's not even possible with Trollstore, since Vē uses hooks.
